server.port=8080

spring.application.name=spring-api

app.security.jwt.secret=${APP_SECURITY_JWT_SECRET:change-this-secret-key-change-this-secret-key-123456}
app.security.jwt.issuer=${APP_SECURITY_JWT_ISSUER:frontend-microservices-lab}
app.security.jwt.expiration-minutes=${APP_SECURITY_JWT_EXPIRATION_MINUTES:60}
